config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :chairs
  resources :subcategories
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :category, presence: true, uniqueness: true
  has_many :subcategories, dependent: :destroy
end

app/models/chair.rb
class Chair < ApplicationRecord
  validates :chair, presence: true, uniqueness: true
  validates :price, numericality: { greater_than: 0 }
  belongs_to :subcategory
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  validates :subcategory, presence: true, uniqueness: true
  belongs_to :category
  has_many :chairs, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :set_admin, only: %i[ new create edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def set_admin
      redirect_to(root_path) unless current_user.is_admin
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/chairs_controller.rb
class ChairsController < ApplicationController
  before_action :set_chair, only: %i[ show edit update destroy ]
  before_action :set_subcategories_for_select, only: %i[ new edit create update ]
  before_action :set_admin, only: %i[ new create edit update destroy ]

  # GET /chairs or /chairs.json
  def index
    @chairs = Chair.all
  end

  # GET /chairs/1 or /chairs/1.json
  def show
  end

  # GET /chairs/new
  def new
    @chair = Chair.new
  end

  # GET /chairs/1/edit
  def edit
  end

  # POST /chairs or /chairs.json
  def create
    @chair = Chair.new(chair_params)

    respond_to do |format|
      if @chair.save
        format.html { redirect_to @chair, notice: "Chair was successfully created." }
        format.json { render :show, status: :created, location: @chair }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chairs/1 or /chairs/1.json
  def update
    respond_to do |format|
      if @chair.update(chair_params)
        format.html { redirect_to @chair, notice: "Chair was successfully updated." }
        format.json { render :show, status: :ok, location: @chair }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chairs/1 or /chairs/1.json
  def destroy
    @chair.destroy
    respond_to do |format|
      format.html { redirect_to chairs_url, notice: "Chair was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chair
      @chair = Chair.find(params[:id])
    end

    def set_admin
      redirect_to(root_path) unless current_user.is_admin
    end

    # Only allow a list of trusted parameters through.
    def chair_params
      params.require(:chair).permit(:subcategory_id, :chair, :price)
    end

    def set_subcategories_for_select
      @subcategories_for_select = []
      Subcategory.select("subcategory, id").each do |row|
        @subcategories_for_select.push([row[:subcategory], row[:id]])
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index

  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: %i[ show edit update destroy ]
  before_action :set_categories_for_select, only: %i[ new edit create update ]
  before_action :set_admin, only: %i[ new create edit update destroy ]

  # GET /subcategories or /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1 or /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories or /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: "Subcategory was successfully created." }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1 or /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: "Subcategory was successfully updated." }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1 or /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: "Subcategory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    def set_admin
      redirect_to(root_path) unless current_user.is_admin
    end

    # Only allow a list of trusted parameters through.
    def subcategory_params
      params.require(:subcategory).permit(:subcategory, :category_id)
    end

    def set_categories_for_select
      @categories_for_select = []
      Category.select("category, id").each do |row|
        @categories_for_select.push([row[:category], row[:id]])
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chairs_helper.rb
module ChairsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <% if current_user.is_admin %>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if current_user.is_admin %>
  <%= link_to 'New Category', new_category_path %><br><br>
<% end %>
<%= link_to 'Subcategories', subcategories_path %>&nbsp; &nbsp; &nbsp;
<%= link_to 'Go Home', root_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<% if current_user.is_admin %>
  <%= link_to 'Edit', edit_category_path(@category) %> |
<% end %>
<%= link_to 'Back', categories_path %>

app/views/chairs/_form.html.erb
<%= form_with(model: chair) do |form| %>
  <% if chair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chair.errors.count, "error") %> prohibited this chair from being saved:</h2>

      <ul>
        <% chair.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subcategory_id, "Належить до підкатегорії" %>
    <%= form.select :subcategory_id, @subcategories_for_select %>
  </div>

  <div class="field">
    <%= form.label :chair, "Назва" %>
    <%= form.text_field :chair %>
  </div>

  <div class="field">
    <%= form.label :price, "Ціна, грн" %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit "Зберегти" %>
  </div>
<% end %>

app/views/chairs/edit.html.erb
<h1>Редагування</h1>

<%= render 'form', chair: @chair %>

<%= link_to 'Показати', @chair %> |
<%= link_to 'Назад', chairs_path %>

app/views/chairs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Стільці, крісла, табурети</h1>

<table>
  <thead>
    <tr>
      <th>Підкатегорія</th>
      <th>Назва</th>
      <th>Ціна, грн</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @chairs.each do |chair| %>
      <tr>
        <td><%= chair.subcategory[:subcategory] %></td>
        <td><%= chair.chair %></td>
        <td><%= number_to_currency(chair.price, separator: ",", delimiter: " ", format: '%n') %></td>
        <td><%= link_to 'Показати', chair %></td>
        <% if current_user.is_admin %>
          <td><%= link_to 'Редаг.', edit_chair_path(chair) %></td>
          <td><%= link_to 'Видалити', chair, method: :delete, data: { confirm: 'Ви впевнені?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.is_admin %>
  <%= link_to 'Додати', new_chair_path %><br><br>
<% end %>
<%= link_to 'До підкатегорій', subcategories_path %>&nbsp; &nbsp; &nbsp;
<%= link_to 'На головну', root_path %>

app/views/chairs/new.html.erb
<h1>Новий товар</h1>

<%= render 'form', chair: @chair %>

<%= link_to 'Назад', chairs_path %>

app/views/chairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Належить до підкатегорії:</strong>
  <%= @chair.subcategory[:subcategory] %>
</p>

<p>
  <strong>Назва:</strong>
  <%= @chair.chair %>
</p>

<p>
  <strong>Ціна:</strong>
  <%= number_to_currency(@chair.price, unit: "грн", separator: ",", delimiter: " ", format: "%n %u") %>
</p>
<% if current_user.is_admin %>
  <%= link_to 'Редагувати', edit_chair_path(@chair) %> |
<% end %>
<%= link_to 'Назад', chairs_path %>

app/views/home/index.html.erb
<h1>Елітна крамниця "12 крісел"</h1>
<h2>Якість понад усе!</h2>
<br>
<% if current_user.nil? %>
  <h3><%= link_to "Вхід", new_user_session_path %></h3>
  <h3><%= link_to "Реєстрація", new_user_registration_path %></h3>
<% else %>
  <table>
    <tr>
      <td>
        <h3 style="width: 700px;">
          <% if current_user.is_admin %>
            Панель адміністратора
          <% else %>
            Ласкаво просимо!
          <% end %>
        </h3>
      </td>
      <td><h3><%= link_to "Вихід", destroy_user_session_path, method: :delete %></h3></td>
    </tr>
  </table>
  <% if current_user.is_admin %>
    <h3><%= link_to "Категорії товарів", categories_path %></h3>
    <h3><%= link_to "Підкатегорії товарів", subcategories_path %></h3>
    <h3><%= link_to "Перелік товарів", chairs_path %></h3>
  <% else %>
    <p>У нас Ви можете замовити зручні та надійні крісла, стільці, табурети для дому та офісу</p>
    <h3><%= link_to "Категорії товарів", categories_path %></h3>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwelveChairs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subcategories/_form.html.erb
<%= form_with(model: subcategory) do |form| %>
  <% if subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
        <% subcategory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subcategory %>
    <%= form.text_field :subcategory %>
  </div>

  <div class="field">
    <%= form.label :category_id, "Belongs to category" %>
    <%= form.select :category_id, @categories_for_select %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subcategories</h1>

<table>
  <thead>
    <tr>
      <th>Subcategory</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.subcategory %></td>
        <td><%= subcategory.category[:category] %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <% if current_user.is_admin %>
          <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
          <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if current_user.is_admin %>
  <%= link_to 'New Subcategory', new_subcategory_path %><br><br>
<% end %>
<%= link_to 'Chairs', chairs_path %>&nbsp; &nbsp; &nbsp;
<%= link_to 'To categories', categories_path %>&nbsp; &nbsp; &nbsp;
<%= link_to 'Go Home', root_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subcategory:</strong>
  <%= @subcategory.subcategory %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subcategory.category[:category] %>
</p>

<% if current_user.is_admin %>
  <%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<% end %>
<%= link_to 'Back', subcategories_path %>